### ISSUE TITLE
device: /dev/dab0 doesn't support the extended media API

### ISSUE THREAD

**Issue by nRaecheR** [Vitalic66/DAB-FM-sundtek-api#1]
First of all, thank you for this interesting and useful project! 

I've one problem but this is a serious one. The program works as expected but I can't get any audio output from it. The scan of the stations is working, I can select one and see the text and picture data but there is no sound. The log output to console shows that there is a lock on the frequency but at the start of the program there is an error message 

```
device: /dev/dab0 doesn't support the extended media API
```

I'm using the latest version of the sundtek driver sundtek_installer_200507.155645.sh and tried it on two different systems, one was a Raspberry Pi with Raspian Buster updated to latest version (kernel 5.4.91+) and the other was a AMD64 system with Ubuntu 20.04 (kernel 5.4 too).

Have you got it working with any of there systems? Thank you very much!

**Comment by Vitalic66** [comment]
Have you installed sundtek driver with "-service"?

Did you do "sudo ldconfig" after install?

It works fine on my Pi4 with latest kernel and Ubuntu 18.04 .

The error message on startup is normal, as the program tries to kill the sundtek mediaserver. Important if program crashed before.

What is the output of aplay -l and aplay -L

**Comment by nRaecheR** [comment]
Thank you for your answer. Yes, I've tried it with both the RPI3 and my Laptop with Ubuntu 20.04 amd64 with the installation with -service parameter and ldconfig. It's the same, the DAB+ text and pictures are shown and the log output states that the tuner is [locked] but I get no sound and the message that the extended media api isn't supported. 

Here's the output from aplay -l :+1: 
```
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: ALC3266 Analog [ALC3266 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
```
and this one is aplay -L : 

```
efault
    Playback/recording through the PulseAudio sound server
surround21
    2.1 Surround output to Front and Subwoofer speakers
surround40
    4.0 Surround output to Front and Rear speakers
surround41
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50
    5.0 Surround output to Front, Center and Rear speakers
surround51
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
null
    Discard all samples (playback) or generate zero samples (capture)
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pulse
    PulseAudio Sound Server
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
sysdefault:CARD=PCH
    HDA Intel PCH, ALC3266 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
hdmi:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 3
    HDMI Audio Output
hdmi:CARD=PCH,DEV=4
    HDA Intel PCH, HDMI 4
    HDMI Audio Output
dmix:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    Direct sample mixing device
dmix:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct sample mixing device
dmix:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Direct sample mixing device
dmix:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Direct sample mixing device
dmix:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Direct sample mixing device
dmix:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Direct sample mixing device
dsnoop:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Direct sample snooping device
dsnoop:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Direct sample snooping device
hw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Direct hardware device without any conversions
hw:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Direct hardware device without any conversions
plughw:CARD=PCH,DEV=0
    HDA Intel PCH, ALC3266 Analog
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 0
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=7
    HDA Intel PCH, HDMI 1
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=8
    HDA Intel PCH, HDMI 2
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=9
    HDA Intel PCH, HDMI 3
    Hardware device with all software conversions
plughw:CARD=PCH,DEV=10
    HDA Intel PCH, HDMI 4
    Hardware device with all software conversions
usbstream:CARD=PCH
    HDA Intel PCH
    USB Stream Output
```

Both are the output on the AMD64 installation. 

I will try the same with a Live-CD of Ubuntu 20.04, a clean installation. I fear that this is a problem with the Sundtek "driver". Sundtek is a company without any support, I've tried to geht the streamer working for half a year without success.

**Comment by nRaecheR** [comment]
I had no success with the Live-CD too. No sound, I even enabled all outputs in alsamixer and installed pavuctl. PA control didn't show a sound source while the application was running and was locked on a station. 
The only difference was that the extended media api error messages only appeared after the first crash of the app. It crashes every time I push the "volume down" (???) button in the setup/scan dialog with a segmentation fault.

**Comment by Vitalic66** [comment]
Have you ever tried the mute unmute button?

And dp you have pavucontrol installed to watch the streams being played through pulseaudio?

Looks like you have many different dmixes. 

If you see picture and textdata, it works. It looks like a pulseaudio problem to me not an api or driver problem.

**Comment by Vitalic66** [comment]
Are you starting the app as sudo?

Maybe i can teamviewer you, if you have installed it.

**Comment by nRaecheR** [comment]
Yes, i've started the program with sudo. I'll try two more things later in the afternoon, first I will try it on another computer with a 18.04 x86 installation and if this won't work a 18.04 Live-CD on the AMD64 Laptop.

If both won't work it's likely that I throw the stick in the trash can because it won't work at all and there is zero support from Sundtek and no fixed/updated version of the driver for 4 months. It seems Sundtek is dead, as the DAB+ stick.

**Comment by Vitalic66** [comment]
I also deleted and reinstalled the newest version. First i had the same problems like you.

So I restarted the app, performed a dab and fm search and after scans i closed the app and restarted it.

Api error was gone. 

I'll have to check the error before the next update.

It's still beta...

**Comment by nRaecheR** [comment]
Good news, it works with my very old x86 (32 bit) laptop with 18.04 installed without any problems. In fact it was the first time I heard any sound from the stick. Will try the 18.04 Live-CD on the 64 bit system later.

**Comment by nRaecheR** [comment]
It's working with 18.04 64 bit too. The "driver" seems to be incompatible with the user space from 20.04 because the 20.04 Live-CD comes with the updated kernel.
Hey Sundtek, it's time to open source the driver and libraries, it seems to be the only chance to get it working on any current distro. The streaming server still crashes but I had it working one time. 

Thank you for your help, now I can use the stick to hear radio locally. The goal was to stream it to mobiles, tablets etc. but this seems to be impossible thanks to the mediocre software support from Sundtek.
